### ISSUE TITLE
Colour correction

### ISSUE THREAD

**Issue by tom-bird** [doda42/LFToolbox#15]
I am decoding LFR images from [this](http://plenodb.jpeg.org/lf/epfl/) dataset with the toolbox.

The decode works, but the colour correction does not seem to be correct (the colours do not match up with the thumbnails, and do not look correct).

I ran `LFUtilProcessWhiteImages` on the camera calibration data (available at the above link) and then  `LFUtilDecodeLytroFolder([], [], DecodeOptions);` on the images after setting`DecodeOptions.OptionalTasks = 'ColourCorrect'`, just as per the documentation.

Do you know what could be going wrong?

**Comment by doda42** [comment]
I suspect you're comparing the toolbox colour correction to the thumbnails produced using Lytro's tools, correct?

The bad news is, the toolbox colour correction as of v0.5 is pretty limited, and does not approach the performance of the Lytro tools. The toolbox has never had the goal of approaching the visual quality of the Lytro's tools, but has rather seeks to provide close to raw data to researchers so they can develop their own tools. This is also why steps like denoising are not performed during decode.

The good news is that, with the help of collaborators @LEPENDUM and @pierredavid , colour correction will be improved in v0.6. https://v-sense.scss.tcd.ie/wp-content/uploads/2020/02/TIP_HQLF_authorV_small.pdf  All that's left is a bit of a documentation push before that's ready for release, and you can try it now by checking out the development branch.

**Comment by tom-bird** [comment]
Well I would guess that the thumbnails are produced using Lytro's tools, but I do not know (the thumbnails are provided by the dataset provider, so I do not know what they used).

Thank you for your answer, I had assumed I was doing something wrong. The colour is not crucial for my application.

**Comment by doda42** [comment]
I was curious if you were comparing to the thumbnails produced by the toolbox.  If there were a mismatch between the toolbox-generated light field and toolbox-generated thumbnail, it could indicate a serious issue.  

If you want to verify colour correction is running correctly, you can also follow the tour in the documentation and do a visual comparison.  Especially for Lytro F01 images, the visual improvement even with the current colour correction is appreciable.

If you don't need colour correction, I recommend not running it.  All forms of colour correction end up amplifying noise. To understand this think of what happens when a dark red needs to become a bright red.
