### ISSUE TITLE
How to use the calibration parameters to get depth map

### ISSUE THREAD

**Issue by backkon** [doda42/LFToolbox#18]
Hi, I have studied the light field toolbox you provided to decode and calibrate LF data, excellent work! But I have a question. After using the calibration parameters to convert (i,j,k,l) to (s,t,u,v), how can I get the true depth map based on the disparity map?

**Comment by backkon** [comment]
when I calibrate my illum camera, the RMSE value I got is very large, and when I use the calibration result to validate, the code reports an error, prompting that the complex number cannot be interpolated.

**Comment by sky-fly97** [comment]
> when I calibrate my illum camera, the RMSE value I got is very large, and when I use the calibration result to validate, the code reports an error, prompting that the complex number cannot be interpolated.

666

**Comment by doda42** [comment]
We're sporadically working on improving stability of the calibration so that it works consistently with Illum imagery. The ThinLens model in the develop0.6 branch works pretty well, but the documentation and release have been waiting for a bit attention before official release. Some have reported using this and having it work for them. I hope to get to this in the next month.

**Comment by doda42** [comment]
To your earlier question, depth and disparity are related through the plenoptic intrinsic matrix. You can read more about this here : http://www-personal.acfr.usyd.edu.au/ddan1654/Dansereau2014Plenoptic.pdf  and there's a handy reference at the back.  If you rectify to a diagonal intrinsic matrix, depth and "disparity" (more generally slope in i,k and j,l) are related by a simple scaling factor, as in stereo vision.
